name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        docker build --tag unit-tests -f unitTests.dockerfile .
        docker run unit-tests
    - name: Build container
      run: |
        docker build -f web.Dockerfile .
