name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        echo Running unit tests
        # docker build --tag unit-tests -f unitTests.dockerfile .
        # docker run unit-tests
    - name: Build container
      run: |
        echo Building web dockerfile
        # docker build -f web.Dockerfile .
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up SSH Key
        env: # Or as an environment variable
          ssh_key: ${{ secrets.VAPOR_CLOUD_SSH_PRIVATE_KEY }}
        run: |
          echo "Environment variable:"
          echo $SSH_KEY
          mkdir -p ~/.ssh && \
          chmod 0700 ~/.ssh && \
          ssh-keyscan github.com > ~/.ssh/known_hosts && \
          ssh-keyscan git.code.vapor.cloud > ~/.ssh/known_hosts
          echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa && \
          chmod 600 ~/.ssh/id_rsa
          echo Key contents
          ls ~/.ssh
          echo Key is
          cat ~/.ssh/id_rsa
          echo Testing SSH connection to VC
          ssh git@git.code.vapor.cloud
      - name: Set up Vapor Cloud Git
        run: |
          pwd
          ls
          git status
          git show-ref
          git remote add cloud git@git.code.vapor.cloud:github-actions-deploy.git
          git push cloud master
      - name: Deploy to Vapor Cloud
        env: # Or as an environment variable
          deploy_key: ${{ secrets.VAPOR_CLOUD_DEPLOY_KEY }}
        run: |
          echo "Deploying to Vapor Cloud"
          curl -X GET https://api.v2.vapor.cloud/v2/apps/environments/3259835F-EB77-4FC0-A446-B2F8FEACF732/trigger?branch=master \
          -H "Authorization: Bearer $DEPLOY_KEY"
