name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        echo Running unit tests
        # docker build --tag unit-tests -f unitTests.dockerfile .
        # docker run unit-tests
    - name: Build container
      run: |
        echo Building web dockerfile
        # docker build -f web.Dockerfile .
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Vapor Cloud Git
        run: |
          pwd
          ls
          git status
          git show-ref
          git remote add cloud git@git.code.vapor.cloud:github-actions-deploy.git
          # git push cloud master
      - name: Deploy to Vapor Cloud
        env: # Or as an environment variable
          deploy_key: ${{ secrets.VAPOR_CLOUD_DEPLOY_KEY }}
        run: |
          echo "Deploying to Vapor Cloud"
          curl -X GET https://api.v2.vapor.cloud/v2/apps/environments/3259835F-EB77-4FC0-A446-B2F8FEACF732/trigger?branch=master \
          -H "Authorization: Bearer $DEPLOY_KEY"
